# Generated by Django 5.2 on 2025-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_autor_created_by_editorial_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
